# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags: 
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew compileJava
        ./gradlew processResources
        ./gradlew classes
        ./gradlew compileTestJava
        ./gradlew processTestResources
        ./gradlew testClasses


  Test:
    needs: Compile
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TestReport
        path: build/reports


  Assemble:
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
          ./gradlew jar
          ./gradlew assemble
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BuildJar
        path: build/libs/*.jar
  Release:
    if: github.event_name=='push' && startsWith(github.ref, 'refs/tags/v')
    needs: Assemble
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - uses: actions/download-artifact@v2
      with:
        name: BuildJar
        path: jar
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: jar/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
